name: Syncing two repo
on:
  push:
    branches:
      - main

env:
  SOURCE_REPO: "git@github.com:M0ugou-club/42SH.git" #Insert source url of the git source repo
  DEST_REPO: "git@github.com:EpitechPromo2027/B-PSU-200-TLS-2-1-42sh-matthias.soual.git" #Insert Destination url of the git dest rep

jobs:
  check_repo:
    name: "Check if the repo is clean"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check_repo
        run: |
          BAD_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
          for FILES in $BAD_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [ "$BAD_FILES" != ""]; then
            exit 1
          fi
            
  git-sync:
    needs: check_repo
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ env.SOURCE_REPO }}
          source_branch: "main"
          destination_repo: ${{ env.DEST_REPO }}
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
